spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test1
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: dlehddud6097@gmail.com # 앱 비밀번호를 발급받은 구글 계정
    password: ztuh izqb rqws doty # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    default-encoding: utf-8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #d??? ?? 3.x, hibernate6

email:
  from:
    address : dlehddud6097@gmail.com
    name : 관리자